export const INIT_ALARM_INFO = 'INIT_ALARM_INFO';
export const INIT_TCG_STATUS = 'INIT_TCG_STATUS';
export const INIT_HOST_NAME = 'INIT_HOST_NAME';
export const INIT_NET_DATA = 'INIT_NET_DATA';
export const INIT_FIRMWARE_DATA = 'INIT_FIRMWARE_DATA';
export const INIT_NTP_DATA = 'INIT_NTP_DATA';
export const INIT_SESSION_DATA = 'INIT_SESSION_DATA';
export const INIT_HEALTH_INFO = 'INIT_HEALTH_INFO';