export const INIT_NETWORK_DATA = 'INIT_NETWORK_DATA';
export const NETWORK_VALUE_CHANGE = 'NETWORK_VALUE_CHANGE';
export const NETWORK_ERRORS_CHANGE = 'NETWORK_ERRORS_CHANGE';
export const JDUGE_DISABLE_STATUS = 'JDUGE_DISABLE_STATUS';